// ── CATEGORÍAS ──
const LOCAL_CATEGORIES = [
    { id: 'pasta',     name: 'Pasta',      emoji: '🍝' },
    { id: 'carnes',    name: 'Carnes',     emoji: '🥩' },
    { id: 'vegano',    name: 'Vegano',     emoji: '🥦' },
    { id: 'postres',   name: 'Postres',    emoji: '🍰' },
    { id: 'sopas',     name: 'Sopas',      emoji: '🍲' },
    { id: 'ensaladas', name: 'Ensaladas',  emoji: '🥗' },
    { id: 'mariscos',  name: 'Mariscos',   emoji: '🦐' },
    { id: 'desayunos', name: 'Desayunos',  emoji: '🍳' },
]

// ── RECETAS ──
const LOCAL_RECIPES = [
    {
        id: '1',
        title: 'Pasta Carbonara Clásica',
        category_id: 'pasta',
        category: { name: 'Pasta', emoji: '🍝' },
        time_minutes: 25,
        difficulty: 'Fácil',
        servings: 2,
        rating: '4.8',
        author_name: 'María López',
        image_url: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=500&q=80',
        description: 'La auténtica carbonara italiana: sin nata, solo huevos, queso pecorino y guanciale.',
        ingredients: '200g espaguetis\n100g guanciale o panceta\n2 yemas de huevo\n1 huevo entero\n80g queso pecorino rallado\nPimienta negra al gusto\nSal para el agua',
        steps: 'Cocer la pasta al dente en agua con sal.\nSaltear el guanciale cortado en tiras hasta que esté dorado.\nMezclar yemas, huevo entero y queso con pimienta generosa.\nEscurrir la pasta reservando un vaso del agua de cocción.\nFuera del fuego, mezclar la pasta con el guanciale y la mezcla de huevos.\nAgregar agua de cocción poco a poco hasta obtener una salsa cremosa.'
    },
    {
        id: '2',
        title: 'Pollo al Limón con Hierbas',
        category_id: 'carnes',
        category: { name: 'Carnes', emoji: '🥩' },
        time_minutes: 40,
        difficulty: 'Media',
        servings: 4,
        rating: '4.6',
        author_name: 'Carlos Ruiz',
        image_url: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500&q=80',
        description: 'Pechuga de pollo jugosa marinada en limón, ajo y romero al horno.',
        ingredients: '4 pechugas de pollo\n2 limones (zumo y ralladura)\n4 dientes de ajo\n2 ramitas de romero fresco\nAceite de oliva\nSal y pimienta\n1 cucharadita de pimentón',
        steps: 'Mezclar zumo de limón, ralladura, ajo picado, romero, aceite, sal, pimienta y pimentón.\nMarinar el pollo en esta mezcla durante al menos 30 minutos.\nPrecalentar el horno a 200°C.\nColocar el pollo en una fuente con la marinada.\nHornear 30-35 minutos, regando con los jugos a mitad de cocción.\nDejar reposar 5 minutos antes de servir.'
    },
    {
        id: '3',
        title: 'Bowl de Quinoa Vegano',
        category_id: 'vegano',
        category: { name: 'Vegano', emoji: '🥦' },
        time_minutes: 20,
        difficulty: 'Fácil',
        servings: 2,
        rating: '4.7',
        author_name: 'Ana Verde',
        image_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&q=80',
        description: 'Bowl nutritivo y colorido con quinoa, aguacate, garbanzos crujientes y tahini.',
        ingredients: '1 taza de quinoa\n1 aguacate\n1 lata de garbanzos\n2 tazas de espinacas\n1 pepino\n10 tomates cherry\nSalsa tahini\nLimón, sal, aceite de oliva',
        steps: 'Cocinar la quinoa según las instrucciones del paquete.\nEscurrir los garbanzos y saltear con aceite, sal y comino hasta que estén crujientes.\nCortar aguacate, pepino y tomates cherry por la mitad.\nMontar el bowl: quinoa de base, luego espinacas, garbanzos, aguacate y verduras.\nAliñar con tahini diluido con limón y agua, ajustar sal.'
    },
    {
        id: '4',
        title: 'Tiramisú Tradicional',
        category_id: 'postres',
        category: { name: 'Postres', emoji: '🍰' },
        time_minutes: 30,
        difficulty: 'Media',
        servings: 8,
        rating: '4.9',
        author_name: 'Giulia Bianchi',
        image_url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80',
        description: 'El postre italiano por excelencia: capas de bizcochos, mascarpone y cacao.',
        ingredients: '500g queso mascarpone\n4 huevos\n100g azúcar\n300ml café espresso frío\n200g bizcochos ladyfinger\n30ml ron o amaretto (opcional)\nCacao en polvo para decorar',
        steps: 'Separar yemas de claras. Batir yemas con azúcar hasta blanquear.\nIncorporar el mascarpone a la mezcla de yemas con movimientos suaves.\nMontar las claras a punto de nieve e incorporar con movimientos envolventes.\nMezclar el café frío con el licor en un plato.\nSumergir brevemente los bizcochos en el café y colocar una capa en el molde.\nExtender la mitad de la crema de mascarpone.\nRepetir con otra capa de bizcochos y crema.\nRefrigerarse al menos 4 horas. Espolvorear cacao antes de servir.'
    },
    {
        id: '5',
        title: 'Crema de Tomate y Albahaca',
        category_id: 'sopas',
        category: { name: 'Sopas', emoji: '🍲' },
        time_minutes: 35,
        difficulty: 'Fácil',
        servings: 4,
        rating: '4.5',
        author_name: 'Pedro Sanz',
        image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&q=80',
        description: 'Sopa cremosa de tomate asado con albahaca fresca y un toque de crema.',
        ingredients: '1kg tomates maduros\n1 cebolla\n4 dientes de ajo\nManojo de albahaca fresca\n500ml caldo de verduras\n100ml nata para cocinar\nAceite de oliva, sal, pimienta\nPizca de azúcar',
        steps: 'Cortar tomates y cebolla en trozos. Colocar en bandeja con ajo y rociar con aceite.\nAsar a 200°C durante 25 minutos hasta que estén dorados.\nPasar las verduras asadas a una olla con el caldo de verduras.\nAñadir la albahaca y triturar hasta obtener una crema lisa.\nColar si se desea una textura más fina.\nIncorporar la nata, sazonar y calentar sin que hierva.'
    },
    {
        id: '6',
        title: 'Ensalada Mediterránea',
        category_id: 'ensaladas',
        category: { name: 'Ensaladas', emoji: '🥗' },
        time_minutes: 15,
        difficulty: 'Fácil',
        servings: 2,
        rating: '4.4',
        author_name: 'Rosa Martín',
        image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&q=80',
        description: 'Ensalada fresca con tomate, pepino, olivas, queso feta y orégano.',
        ingredients: '3 tomates maduros\n1 pepino\n1/2 cebolla roja\n150g queso feta\nAceitunas negras kalamata\nOrégano seco\nAceite de oliva virgen extra\nSal y pimienta',
        steps: 'Cortar tomates en gajos, pepino en rodajas y cebolla en aros finos.\nColocar en un cuenco amplio.\nAñadir las aceitunas y desmenuzar el queso feta por encima.\nEspolvorear orégano generosamente.\nAliñar con aceite de oliva, sal y pimienta al gusto.\nDejar reposar 5 minutos antes de servir para que se mezclen los sabores.'
    },
    {
        id: '7',
        title: 'Gambas al Ajillo',
        category_id: 'mariscos',
        category: { name: 'Mariscos', emoji: '🦐' },
        time_minutes: 15,
        difficulty: 'Fácil',
        servings: 4,
        rating: '4.8',
        author_name: 'Manolo García',
        image_url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=500&q=80',
        description: 'Tapas clásicas españolas: gambas saltadas con ajo, guindilla y aceite de oliva.',
        ingredients: '500g gambas peladas\n6 dientes de ajo laminados\n2 guindillas secas\n100ml aceite de oliva virgen extra\nSal gorda\nPerejil fresco picado\nPan para acompañar',
        steps: 'Calentar el aceite en una cazuela de barro o sartén a fuego alto.\nAñadir el ajo laminado y la guindilla. Saltear 30 segundos.\nAgregar las gambas y saltear 2-3 minutos hasta que estén rosadas.\nSazonar con sal y retirar del fuego inmediatamente.\nEspolvorear perejil fresco y servir al momento en la misma cazuela.'
    },
    {
        id: '8',
        title: 'Tostadas con Aguacate y Huevo',
        category_id: 'desayunos',
        category: { name: 'Desayunos', emoji: '🍳' },
        time_minutes: 10,
        difficulty: 'Fácil',
        servings: 1,
        rating: '4.6',
        author_name: 'Laura Vega',
        image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&q=80',
        description: 'El desayuno favorito: pan tostado con aguacate, huevo poché y semillas.',
        ingredients: '2 rebanadas de pan integral\n1 aguacate maduro\n2 huevos\nJugo de medio limón\nSal, pimienta y chile en hojuelas\nSemillas de sésamo\nMicrobrotes para decorar (opcional)',
        steps: 'Tostar el pan hasta que esté dorado y crujiente.\nAplastar el aguacate con un tenedor, añadir limón, sal y pimienta.\nExtender el aguacate sobre las tostadas.\nHervir agua con un chorrito de vinagre en un cazo pequeño.\nCrear un remolino en el agua y deslizar el huevo para pocharlo 3 minutos.\nColocar el huevo poché encima, sazonar y añadir chile y sésamo.'
    }
]
